spring.application.name=platform-api

spring.datasource.url=jdbc:postgresql://localhost:5432/utility_hub
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# AWS S3 Configuration
aws.s3.bucket-name=utility-hub-library
aws.s3.presigned-url-expiration=15
aws.profile-name=Hometown
aws.region=us-east-2
