spring.application.name=platform-api

spring.datasource.url=jdbc:postgresql://localhost:5432/book_utility
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

